# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy - Admin API

on:
  push:
    branches: [ main ]
    paths:
      - 'src/API/Orchestration/ReservationSystem.Orchestration.Admin/**'
      - '.github/workflows/main_reservation-system-db-api-admin.yml'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/API/Orchestration/ReservationSystem.Orchestration.Admin' # path to the Admin API project directory
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1FF3C77BEFF345508A1C21498E76C5F1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4CB9FBACAC2D48FAAA86A101A25D3FF8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_01BDBBAA2F66484A85CC69715F897A4D }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'reservation-system-db-api-admin'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

