# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# Seb Harvey

name: Build and deploy - Retail API

on:
  push:
    branches: [ main ]
    paths:
      - 'src/API/Orchestration/ReservationSystem.Orchestration.Retail/**'
      - '.github/workflows/main_reservation-system-db-api-retail.yml'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/API/Orchestration/ReservationSystem.Orchestration.Retail' # path to the Retail API project directory
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F39351B26CCF48D3986CECA1E60200EF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CC6B15081A204B42B2A8D4322C53497D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1AC359B6AD3E452F9B163E2F16C15E2B }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'reservation-system-db-api-retail'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

