# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# Seb Harvey

name: Build and deploy - Order Microservice

on:
  push:
    branches: [ main ]
    paths:
      - 'src/API/Microservices/ReservationSystem.Microservices.Order/**'
      - 'src/API/Shared/**'
      - '.github/workflows/main_reservation-system-db-microservice-order.yml'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/API/Microservices/ReservationSystem.Microservices.Order' # path to the Order Microservice project directory
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0A993510A15043818AE4ECA46345051C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5DE6B0D3D9F7428E89F7C37AFFED8F39 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0E66E3109FF4A2D9D100E9BB049BBF1 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'reservation-system-db-microservice-order'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

