#!/usr/bin/env python3
"""
Stop hook — prompt & token accounting for harness refinement.

Fires once each time Claude finishes responding to a prompt. Reads the
session transcript, isolates the turn that just completed (everything since
the last human prompt), and appends a record to `.claude/prompt-stats.md`
capturing:

  * the prompt that was issued
  * how many tokens were spent generating the response (with a full
    input / cache / output breakdown)
  * what context was used to produce it — files read/edited, tools invoked,
    skills and sub-agents launched, and the peak context-window size

These records are intended to be reviewed to refine the prompts and the
context supplied to the harness over time.

The hook is strictly observational: it never blocks and always exits 0.
"""

import json
import os
import sys
from datetime import datetime, timezone

STATS_FILE = os.path.join(
    os.path.dirname(__file__), "..", "..", ".claude", "prompt-stats.md"
)

# Tool inputs whose target is worth recording as "context used".
_PATH_KEYS = ("file_path", "path", "pattern", "notebook_path")

_HEADER = """# Prompt & token statistics

Auto-generated by `scripts/hooks/stop.py` (the Stop hook). One entry is
appended each time Claude finishes responding to a prompt. Use these records
to refine the prompts and the context supplied to the harness.

Token terms:

- **Output** — tokens generated to produce the response (the "result" cost).
- **Input (new)** — fresh, uncached input tokens sent to the model.
- **Cache creation** — input tokens written to the prompt cache this turn.
- **Cache read** — input tokens served from the prompt cache (reused context).
- **Peak context** — largest single-call context window used during the turn
  (input + cache read + cache creation), i.e. how much context was in play.

---
"""


def _read_transcript(path):
    entries = []
    try:
        with open(path, "r") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    entries.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    except OSError:
        pass
    return entries


def _is_human_prompt(entry):
    """True for a genuine human turn (not a tool result or synthetic message)."""
    if entry.get("type") != "user":
        return False
    if entry.get("isSidechain"):
        return False
    if entry.get("origin", {}).get("kind") == "human":
        return True
    # Fallback: string content and no tool-result payload.
    content = entry.get("message", {}).get("content")
    return isinstance(content, str) and not entry.get("toolUseResult")


def _prompt_text(entry):
    content = entry.get("message", {}).get("content", "")
    if isinstance(content, str):
        return content.strip()
    parts = []
    if isinstance(content, list):
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                parts.append(block.get("text", ""))
    return "\n".join(parts).strip()


def _fmt(n):
    return f"{n:,}"


def _tool_target(tool_input):
    if not isinstance(tool_input, dict):
        return None
    for key in _PATH_KEYS:
        val = tool_input.get(key)
        if isinstance(val, str) and val:
            return val
    return None


def _collect_turn(entries):
    """Return (prompt_entry, assistant_msgs) for the most recent turn."""
    last_human = None
    for idx, entry in enumerate(entries):
        if _is_human_prompt(entry):
            last_human = idx
    if last_human is None:
        return None, []
    assistants = [
        e for e in entries[last_human + 1:] if e.get("type") == "assistant"
    ]
    return entries[last_human], assistants


def _summarise(assistants):
    totals = {
        "input_tokens": 0,
        "cache_creation_input_tokens": 0,
        "cache_read_input_tokens": 0,
        "output_tokens": 0,
    }
    peak_context = 0
    model = None
    tool_counts = {}
    context_targets = []  # (tool, target) preserving first-seen order
    seen_targets = set()

    for msg in assistants:
        message = msg.get("message", {})
        model = message.get("model") or model
        usage = message.get("usage", {})
        for key in totals:
            totals[key] += int(usage.get(key, 0) or 0)
        ctx = (
            int(usage.get("input_tokens", 0) or 0)
            + int(usage.get("cache_read_input_tokens", 0) or 0)
            + int(usage.get("cache_creation_input_tokens", 0) or 0)
        )
        peak_context = max(peak_context, ctx)

        for block in message.get("content", []):
            if not isinstance(block, dict) or block.get("type") != "tool_use":
                continue
            name = block.get("name", "tool")
            tool_counts[name] = tool_counts.get(name, 0) + 1
            target = _tool_target(block.get("input", {}))
            if name == "Skill":
                target = block.get("input", {}).get("skill", target)
            elif name in ("Agent", "Task"):
                target = block.get("input", {}).get(
                    "subagent_type", block.get("input", {}).get("description", target)
                )
            if target:
                key = (name, target)
                if key not in seen_targets:
                    seen_targets.add(key)
                    context_targets.append(key)

    return {
        "totals": totals,
        "peak_context": peak_context,
        "model": model or "unknown",
        "tool_counts": tool_counts,
        "context_targets": context_targets,
        "steps": len(assistants),
    }


def _render(prompt, summary, session_id):
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    t = summary["totals"]
    total = sum(t.values())

    lines = []
    short_sid = (session_id or "unknown")[:8]
    lines.append(
        f"## {ts} — session `{short_sid}` — {_fmt(t['output_tokens'])} out / "
        f"{_fmt(total)} total"
    )
    lines.append("")
    lines.append("**Prompt**")
    lines.append("")
    prompt = prompt or "(empty)"
    for pl in prompt.splitlines() or [""]:
        lines.append(f"> {pl}")
    lines.append("")
    lines.append(f"**Model:** `{summary['model']}`")
    lines.append("")
    lines.append("**Tokens**")
    lines.append("")
    lines.append("| Metric | Tokens |")
    lines.append("|--------|-------:|")
    lines.append(f"| Output (generation) | {_fmt(t['output_tokens'])} |")
    lines.append(f"| Input (new) | {_fmt(t['input_tokens'])} |")
    lines.append(f"| Cache creation | {_fmt(t['cache_creation_input_tokens'])} |")
    lines.append(f"| Cache read (reused) | {_fmt(t['cache_read_input_tokens'])} |")
    lines.append(f"| **Total** | **{_fmt(total)}** |")
    lines.append(f"| Peak context window | {_fmt(summary['peak_context'])} |")
    lines.append("")
    lines.append("**Context used**")
    lines.append("")
    lines.append(f"- Assistant steps (inference calls): {summary['steps']}")
    if summary["tool_counts"]:
        tools = ", ".join(
            f"{name} ×{count}"
            for name, count in sorted(
                summary["tool_counts"].items(), key=lambda kv: (-kv[1], kv[0])
            )
        )
        lines.append(f"- Tools invoked: {tools}")
    else:
        lines.append("- Tools invoked: none")
    if summary["context_targets"]:
        lines.append("- Files / targets touched:")
        for name, target in summary["context_targets"][:40]:
            lines.append(f"  - `{target}` ({name})")
        extra = len(summary["context_targets"]) - 40
        if extra > 0:
            lines.append(f"  - … and {extra} more")
    lines.append("")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def main():
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)

    transcript_path = payload.get("transcript_path")
    session_id = payload.get("session_id", "")
    if not transcript_path:
        sys.exit(0)

    entries = _read_transcript(transcript_path)
    prompt_entry, assistants = _collect_turn(entries)
    if prompt_entry is None or not assistants:
        sys.exit(0)

    prompt = _prompt_text(prompt_entry)
    summary = _summarise(assistants)
    record = _render(prompt, summary, session_id)

    os.makedirs(os.path.dirname(STATS_FILE), exist_ok=True)
    new_file = not os.path.exists(STATS_FILE) or os.path.getsize(STATS_FILE) == 0
    with open(STATS_FILE, "a") as fh:
        if new_file:
            fh.write(_HEADER + "\n")
        fh.write(record)

    sys.exit(0)


if __name__ == "__main__":
    main()
